CREATE TABLE SubscribeUsers (
    id SERIAL PRIMARY KEY,
    cryptoID FLOAT NOT NULL,
    email VARCHAR(100) NOT NULL,
    "LIMIT" INTEGER,
    "OFFSET" INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);