CREATE TABLE CryptoUsers (
    id SERIAL PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(100) unique NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);